---
title: "Final Scratch Work"
output: html_document
date: "2023-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(emoji)
library(dplyr)
library(ggimage)
library(emojifont)
library(shiny)
library(shinydashboard)
library(ggplot2)
library(stringr)
library(forcats)
library(dplyr)
library(plotly)
library(highcharter)
library(DT)
library(tidyverse)
library(leaflet)
library(RColorBrewer)
library(leaflegend)
library(sf)
library(usmap)
library(ggplot2)
library(maps)
library(ggthemes)
library(readxl)
library(stringr)
library(urbnmapr)
library(leaflet.extras)
library(dplyr)
library(tidyverse)
library(janitor)
library(ggplot2)
library(scales)
library(plotly)
library(DT)
library(highcharter)
library(igraph)
library(tidygraph)
library(ggraph)
library(visNetwork)
library(ggimage)
library(plotly)
library(ggthemes)



```


### Loading data
```{r}
price <- read.csv("data/CPI_Data/ap.data.3.Food.csv")
price_code <- read.csv("data/CPI_Data/ap.item.csv")
usda <- read.csv("data/USDA_Data/annual_crop_yield_and_price_2002-2023.csv")

# merge in CPI descriptions with CPI data
price$item_code <- price$series_id
price$item_code <- gsub("APU0000",'',price$item_code)
price$item_code <- gsub("APU0100",'',price$item_code)
price$item_code <- gsub("APU0200",'',price$item_code)
price$item_code <- gsub("APU0300",'',price$item_code)
price$item_code <- gsub("APU0400",'',price$item_code)

price <- merge(price, price_code, by="item_code")


#From Chiamaka's code:
# Upload the U.S. world wide agricultural trade partners data set

#trade_partners <- read.csv('data/FAO_Data/FAO_data_US_import_export_partners_2001-2021_crops_A-D.csv')

# Upload the U.S. crop trade value data set

#trade_value <- read.csv('data/FAO_Data/FAO_data_import_export_crops_A-D_valueovertime_2001-2021.csv')
trade_yield <- read.csv('data/FAO_Data/FAO_data_US_annual_yield_production_2001-2021.csv')

# Clean up the column names of the datasets
#trade_partners <- clean_names(trade_partners)
#trade_value <- clean_names(trade_value)
trade_yield <- clean_names(trade_yield)




```


### production yearly plot - fao data 




```{r}

trade_yield$image <-"data/emojis/Bud.png"

make_production_plot <- function(fruit_veg, y_p,unit, icon_point="Bud"){ 
  
  production_table <- trade_yield %>% 
  filter(item == fruit_veg, element == y_p, unit == unit ) %>% 
  mutate(image = paste0("data/emojis/",icon_point,".png")) 
  
ggplot(production_table) + 
    geom_line(aes(x=year, y = value, color="#fc8d62"), size=.5, show.legend = FALSE) +
    geom_point(aes(x=year, y = value), size=.5) +
    geom_image(aes(x=year, y = value,image= image), size=.03) +
    labs(x="Year",y=paste0(y_p," of ",fruit_veg, " (",unit,")")) + theme_minimal() + theme(axis.title.y = element_text(margin = margin(r = 20)),axis.title.x = element_text(margin = margin(t = 20))) 

}



make_production_plot("Apples", "Yield","hg/ha","Apples")
#make_production_plot("Apples", "Production","Tonnes","Apples")
#make_production_plot("Pears", "Yield","hg/ha","Pears")
#make_production_plot("Pears", "Production","Tonnes","Pears")


#make_production_plot("PEARS","TONS", "pear")
#make_production_plot("GRAPES","TONS","grapes")
```

### production yearly plot - usda

```{r}
#
usda <- read.csv("data/USDA_Data/annual_crop_yield_and_price_2002-2023.csv")
usda$Value_numeric <- as.numeric(gsub(",","",usda$Value))


make_production_plot <- function(fruit_veg,unit,icon_point){
  filter(usda, Data.Item == paste0(fruit_veg, " - PRODUCTION, MEASURED IN ", unit)) %>% 
  ggplot() + 
    geom_line(aes(x=Year, y = Value_numeric), color="green",size=.5) +
    geom_point(aes(x=Year, y = Value_numeric), color="green", size=.5) +
    geom_text(label = emoji(icon_point),  size=6.5,family="EmojiOne",color="#255328",aes(x=Year, y = Value_numeric)) +
   # gg_image(aes(image= fruit_veg))
    labs(x="Year",y=paste0(unit," of ",fruit_veg)) 

}

make_production_plot("APPLES", "LB","apple")
make_production_plot("PEARS","TONS", "pear")
make_production_plot("GRAPES","TONS","grapes")
```


### Maps - GGPLOT

```{r, warnings=FALSE}

#read in state files
state1 <- read.csv("data/USDA_Data/state_usda_2022_2011.csv")
state2 <- read.csv("data/USDA_Data/state_usda_2010_2002.csv")
usda_state <- rbind(state1, state2)

#make state map
usstate_sf <- get_urbn_map("states", sf = TRUE)
usstate_sf["State"] <- usstate_sf["state_name"]
usstate_sf["State"] <- toupper(usstate_sf$"State")

#make file with geometry data
usda_state_maps <- merge(usstate_sf,usda_state,by="State")
#st_transform(usda_state_maps, "+proj=longlat +datum=WGS84")

usda_state_maps$Value_numeric <- as.numeric(gsub(",","",usda_state_maps$Value))



```


```{r, warning=FALSE}
#when only filter in making the plot, it only includes 26 states and that is making the map strange. 
#add in state level names? 

make_production_map <- function(fruit_veg, unit,year) {
  data_year <- filter(usda_state, Data.Item == paste0(fruit_veg, " - PRODUCTION, MEASURED IN ", unit),Year == year)
  data_year_map <-  merge(usstate_sf,data_year,by="State",all=TRUE)
  data_year_map$Value_numeric <- as.numeric(gsub(",","",data_year_map$Value))
 map <- ggplot() + 
  #geom_sf(data = usstate_sf , fill = NA, color = "#EEEEEE", size = 1) + 
  geom_sf(data = data_year_map, color="#EEEEEE", aes(fill = Value_numeric)) +
  scale_fill_continuous(name = paste0(fruit_veg, "Produced (", unit,")"), label = scales::comma, low = "green", high = "#023020",na.value="#EEEEEE") + 
  theme_map() + 
  theme(legend.position = "right") + 
  labs(title = paste0(unit," of ",fruit_veg," Produced in ", year, " by State")) 
  return(map)
}

make_production_map("PEACHES","TONS","2017")
make_production_map("BROCCOLI","CWT","2017")
#make_production_map("APPLES","LB","2017")
#make_production_map("ORANGES, MID & NAVEL, UTILIZED","TONS","2017")
#make_production_map("CABBAGE","CWT","2017")
#make_production_map("CAULIFLOWER","CWT","2017")
#make_production_map("LEMONS, UTILIZED","TONS","2017")
#make_production_map("MELONS, WATERMELON","CWT","2017")
#make_production_map("SPINACH","CWT","2017")
#make_production_map("CARROTS","CWT","2017")
#make_production_map("ASPARAGUS, UTILIZED","CWT","2017")
#make_production_map("BEANS, SNAP","CWT","2017")
#make_production_map("CELERY","CWT","2017")
#make_production_map("CUCUMBERS","CWT","2017")
#make_production_map("GARLIC","CWT","2017")
#make_production_map("GRAPEFRUIT, UTILIZED","TONS","2017")
#make_production_map("GRAPES","TONS","2017")
#make_production_map("LETTUCE, ROMAINE, UTILIZED","CWT","2017")
#make_production_map("MELONS, CANTALOUP","CWT","2017")
#make_production_map("SPINACH","CWT","2017")
#make_production_map("ARTICHOKES, UTILIZED","CWT","2017")
#make_production_map("ONIONS, DRY, UTILIZED","CWT","2017")
#make_production_map("PEARS","TONS","2017")
#make_production_map("PEPPERS, BELL, UTILIZED","CWT","2017")
#make_production_map("PEPPERS, CHILE","CWT","2017")
#make_production_map("POTATOES","CWT","2017")
#make_production_map("PUMPKINS","CWT","2017")
#make_production_map("SQUASH","CWT","2017")
#make_production_map("SWEET CORN","CWT","2017")
#make_production_map("SWEET POTATOES","CWT","2017")
#make_production_map("TANGERINES, UTILIZED","TONS","2017")
#make_production_map("TOMATOES, IN THE OPEN, UTILIZED","CWT","2017")


```




### Maps - Leaflet 

```{r,echo=FALSE,warning=FALSE}



make_production_map2 <- function(fruit_veg, unit,year) {
  data_year <- filter(usda_state, Data.Item == paste0(fruit_veg, " - PRODUCTION, MEASURED IN ", unit),Year == year)
  data_year_map <-  merge(usstate_sf,data_year,by="State",all=TRUE)
  data_year_map <- st_transform(data_year_map, "+proj=longlat +datum=WGS84")
  data_year_map$Value_numeric <- as.numeric(gsub(",","",data_year_map$Value))
  pal <- colorNumeric(palette = c("green","#023020"),domain=data_year_map$Value_numeric)
  content <- paste(data_year_map$State,
                 " PRODUCTION:",data_year_map$Value_numeric)
  map <- leaflet(data_year_map) %>%
    addPolygons(data = data_year_map, 
              fillColor = ~pal(Value_numeric), 
              fillOpacity = 1, 
              color = "#EEEEEE",
              weight = 0.5, 
              label = content)  %>%
              #popupOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"), textsize = "15px", direction = "auto")) %>%
      addLegend(position = "bottomright", 
            pal = pal, 
            values = data_year_map$Value_numeric,
            title = paste0(fruit_veg, " PRODUCED IN ", unit), 
            opacity = 1)  %>%
      setMapWidgetStyle(list(background= "white"))
   return(map)
}

make_production_map2("BROCCOLI","CWT","2017")



```



```{r}
#make_production_map2("BROCCOLI","CWT","2017")
#make_production_map2("APPLES","LB","2017")
#make_production_map2("ORANGES, MID & NAVEL, UTILIZED","TONS","2017")
#make_production_map2("CABBAGE","CWT","2017")
#make_production_map2("CAULIFLOWER","CWT","2017")
#make_production_map2("LEMONS, UTILIZED","TONS","2017")
#make_production_map2("MELONS, WATERMELON","CWT","2017")
#make_production_map2("CARROTS","CWT","2017")
#make_production_map2("BEANS, SNAP","CWT","2017")
#make_production_map2("CELERY","CWT","2017")
#make_production_map2("GARLIC","CWT","2017")
#make_production_map2("GRAPEFRUIT, UTILIZED","TONS","2017")
#make_production_map2("GRAPES","TONS","2017")
#make_production_map2("LETTUCE, ROMAINE, UTILIZED","CWT","2017")
#make_production_map2("MELONS, CANTALOUP","CWT","2017")
#make_production_map2("ARTICHOKES, UTILIZED","CWT","2017")
#make_production_map2("PEARS","TONS","2017")
#make_production_map2("PEPPERS, BELL, UTILIZED","CWT","2017")
#make_production_map2("PEPPERS, CHILE","CWT","2017")
#make_production_map2("PUMPKINS","CWT","2017")
#make_production_map2("SQUASH","CWT","2017")
#make_production_map2("SWEET CORN","CWT","2017")
#make_production_map2("TANGERINES, UTILIZED","TONS","2017")
#make_production_map2("TOMATOES, IN THE OPEN, UTILIZED","CWT","2017")
#make_production_map2("ASPARAGUS, UTILIZED","CWT","2017")
#make_production_map2("SPINACH","CWT","2017")
#make_production_map2("CUCUMBERS","CWT","2017")
#make_production_map2("ONIONS, DRY, UTILIZED","CWT","2017")
#make_production_map2("POTATOES","CWT","2017")
#make_production_map2("SWEET POTATOES","CWT","2017")



```




